CREATE TABLE `categories` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) DEFAULT 0,
  `tree_id` int(11) DEFAULT NULL,
  `level` int(11) DEFAULT NULL,
  `parent_tree` varchar(255) DEFAULT NULL,
  `is_fixed` tinyint(1) NOT NULL DEFAULT 0,
  `parent_name` varchar(150) DEFAULT NULL,
  `name` varchar(250) NOT NULL,
  `slug` varchar(255) DEFAULT NULL,
  `image` varchar(250) DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT 0,
  `title_meta_tag` varchar(255) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `keywords` varchar(500) DEFAULT NULL,
  `category_order` mediumint(9) DEFAULT 0,
  `homepage_order` mediumint(9) DEFAULT 1,
  `visibility` tinyint(1) DEFAULT 1,
  `is_bookset` tinyint(1) NOT NULL DEFAULT 0,
  `show_on_homepage` tinyint(1) DEFAULT 0,
  `storage` varchar(20) DEFAULT 'local',
  `image_1` varchar(255) DEFAULT NULL,
  `image_2` varchar(255) DEFAULT NULL,
  `show_image_on_navigation` tinyint(1) NOT NULL DEFAULT 1,
  `bg_color` varchar(10) DEFAULT '#cce6ff',
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `slug` (`slug`),
  KEY `id` (`id`,`parent_id`,`category_order`,`homepage_order`,`visibility`,`is_bookset`,`show_on_homepage`,`storage`,`show_image_on_navigation`),
  KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=106 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
