CREATE TABLE `customer` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` enum('customer','leads') NOT NULL DEFAULT 'customer',
  `company_id` varchar(255) DEFAULT NULL,
  `company_name` varchar(250) NOT NULL,
  `address` longtext DEFAULT NULL,
  `address_2` mediumtext DEFAULT NULL,
  `state_id` int(11) DEFAULT NULL,
  `state_name` varchar(50) DEFAULT NULL,
  `city_id` int(11) DEFAULT NULL,
  `city_name` varchar(50) DEFAULT NULL,
  `pincode` varchar(250) DEFAULT NULL,
  `gst_name` varchar(250) DEFAULT NULL,
  `gst_no` varchar(250) DEFAULT NULL,
  `owner_name` varchar(255) DEFAULT NULL,
  `owner_email` varchar(255) DEFAULT NULL,
  `owner_mobile` varchar(15) DEFAULT NULL,
  `owner_whatsapp` varchar(15) DEFAULT NULL,
  `pm_name` varchar(255) DEFAULT NULL,
  `pm_email` varchar(255) DEFAULT NULL,
  `pm_mobile` varchar(15) DEFAULT NULL,
  `pm_whatsapp` varchar(15) DEFAULT NULL,
  `other_name` varchar(255) DEFAULT NULL,
  `other_email` varchar(255) DEFAULT NULL,
  `other_mobile` varchar(15) DEFAULT NULL,
  `other_whatsapp` varchar(15) DEFAULT NULL,
  `status` enum('fresh','lost','follow','') NOT NULL DEFAULT '',
  `status_label` varchar(255) DEFAULT NULL,
  `status_date` datetime DEFAULT NULL,
  `remark` text DEFAULT NULL,
  `is_move` tinyint(1) NOT NULL DEFAULT 0,
  `move_date` datetime DEFAULT NULL,
  `outstanding` DECIMAL(16,2) NOT NULL DEFAULT 0.00,
  `added_by_id` int(11) DEFAULT NULL,
  `added_by_name` varchar(100) DEFAULT NULL,
  `added_date` datetime NOT NULL,
  `is_deleted` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
