CREATE TABLE `customer_payment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) NOT NULL,
  `type` enum('customer','manual') NOT NULL DEFAULT 'customer',
  `customer_id` int(11) DEFAULT NULL,
  `customer_name` varchar(255) DEFAULT NULL,
  `date` date NOT NULL,
  `inv_no` varchar(255) NOT NULL,
  `amount` decimal(16,2) NOT NULL DEFAULT 0.00,
  `payment_type` enum('official','unofficial') NOT NULL DEFAULT 'official',
  `payment_method` enum('cash','cheque') NOT NULL DEFAULT 'cash',
  `payment_mode` enum('payment','return') NOT NULL DEFAULT 'payment',
  `company_bank` int(11) DEFAULT NULL,
  `company_bank_account` varchar(255) DEFAULT NULL,
  `narration` text DEFAULT NULL,
  `is_approved` tinyint(1) NOT NULL DEFAULT 0,
  `approval_date` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0,
  `added_by` int(11) DEFAULT NULL,
  `added_by_name` varchar(255) DEFAULT NULL,
  `added_date` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
