CREATE TABLE `customer_payment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `customer_id` int(11) NOT NULL,
  `customer_name` varchar(255) DEFAULT NULL,
  `date` date NOT NULL,
  `inv_no` varchar(255) NOT NULL,
  `amount` decimal(16,2) NOT NULL DEFAULT 0.00,
  `payment_type` enum('official','unofficial') NOT NULL DEFAULT 'official',
  `payment_method` enum('cash','bank') NOT NULL DEFAULT 'cash',
  `company_bank_account` int(11) DEFAULT NULL,
  `narration` text DEFAULT NULL,
  `invoices_selected_count` int(11) NOT NULL DEFAULT 0,
  `balance_after` decimal(16,2) NOT NULL DEFAULT 0.00,
  `total_outstanding` decimal(16,2) NOT NULL DEFAULT 0.00,
  `allocated_inv` decimal(16,2) NOT NULL DEFAULT 0.00,
  `total_tender` decimal(16,2) NOT NULL DEFAULT 0.00,
  `on_account` decimal(16,2) NOT NULL DEFAULT 0.00,
  `adjustments` decimal(16,2) NOT NULL DEFAULT 0.00,
  `added_by` int(11) DEFAULT NULL,
  `added_by_name` varchar(255) DEFAULT NULL,
  `added_date` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
