CREATE TABLE `formula_product_in` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) NOT NULL,
  `batch_no` varchar(255) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `product_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `qty` int(11) NOT NULL,
  `total_off_cost` decimal(16,2) NOT NULL DEFAULT 0.00,
  `off_cost_pc` decimal(16,2) NOT NULL DEFAULT 0.00,
  `total_black_cost` decimal(16,2) NOT NULL DEFAULT 0.00,
  `black_cost_pc` decimal(16,2) NOT NULL DEFAULT 0.00,
  `total_actual_cost` decimal(16,2) NOT NULL DEFAULT 0.00,
  `actual_cost_pc` decimal(16,2) NOT NULL DEFAULT 0.00,
  `total_expense` decimal(16,2) NOT NULL DEFAULT 0.00,
  `final_total` decimal(16,2) NOT NULL DEFAULT 0.00,
  `remark` text DEFAULT NULL,
  `added_by` int(11) DEFAULT NULL,
  `added_by_name` varchar(255) DEFAULT NULL,
  `added_date` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
