CREATE TABLE `inventory_dupl_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) NOT NULL,
  `warehouse_id` int(11) NOT NULL,
  `warehouse_name` varchar(250) NOT NULL,
  `product_id` int(11) NOT NULL,
  `product_name` varchar(250) NOT NULL,
  `order_id` int(11) NOT NULL,
  `status` enum('pending','completed','') NOT NULL DEFAULT 'pending',
  `quantity` int(11) NOT NULL,
  `received_date` date DEFAULT NULL,
  `batch_no` varchar(250) DEFAULT NULL,
  `expiry_date` date DEFAULT NULL,
  `invoice_no` varchar(250) DEFAULT NULL,
  `received_amount` decimal(16,2) NOT NULL DEFAULT 0.00,
  `approved_date` date DEFAULT NULL,
  `sample_qty` varchar(250) DEFAULT NULL,
  `ar_no` varchar(250) DEFAULT NULL,
  `added_date` datetime NOT NULL,
  `added_by_id` int(11) NOT NULL,
  `added_by_name` varchar(250) DEFAULT NULL,
  `completed_by_id` int(11) DEFAULT NULL,
  `completed_by_name` varchar(250) DEFAULT NULL,
  `completed_date` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
