CREATE TABLE `inventory` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `supplier_id` int(11) DEFAULT NULL,
  `company_id` int(11) DEFAULT NULL,
  `warehouse_id` int(11) NOT NULL,
  `warehouse_name` varchar(250) NOT NULL,
  `product_id` int(11) NOT NULL,
  `product_name` varchar(250) NOT NULL,
  `categories` varchar(255) NOT NULL,
  `sku` varchar(255) NOT NULL,
  `item_code` varchar(250) DEFAULT NULL,
  `quantity` int(11) NOT NULL,
  `actual_rmb` decimal(15,2) NOT NULL DEFAULT 0.00,
  `total_rmb` decimal(15,2) NOT NULL DEFAULT 0.00,
  `actual_usd` decimal(15,2) DEFAULT 0.00,
  `official_qty` int(11) NOT NULL DEFAULT 0,
  `official_rate_rs` decimal(15,2) NOT NULL DEFAULT 0.00,
  `official_total_rs` decimal(15,2) NOT NULL DEFAULT 0.00,
  `actual_inr` decimal(15,2) DEFAULT 0.00,
  `black_qty` int(11) NOT NULL DEFAULT 0,
  `pending_qty` int(11) NOT NULL DEFAULT 0,
  `duty_percent` decimal(5,2) NOT NULL DEFAULT 0.00,
  `duty_amt` decimal(15,2) NOT NULL DEFAULT 0.00,
  `duty_surcharge` decimal(15,2) NOT NULL DEFAULT 0.00,
  `taxable_value` decimal(15,2) NOT NULL DEFAULT 0.00,
  `gst_amt` decimal(15,2) NOT NULL DEFAULT 0.00,
  `total_amt` decimal(15,2) NOT NULL DEFAULT 0.00,
  `batch_no` varchar(250) DEFAULT NULL,
  `barcode_no` varchar(255) DEFAULT NULL,
  `barcode_url` varchar(255) DEFAULT NULL,
  `po_row_id` int(11) NOT NULL DEFAULT 0,
  `expiry_date` date DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
