CREATE TABLE `inventory_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `supplier_id` int(11) DEFAULT NULL,
  `company_id` int(11) DEFAULT NULL,
  `parent_id` int(11) NOT NULL,
  `warehouse_id` int(11) NOT NULL,
  `warehouse_name` varchar(250) NOT NULL,
  `product_id` int(11) NOT NULL,
  `product_name` varchar(250) NOT NULL,
  `categories` varchar(255) NOT NULL,
  `sku` varchar(255) NOT NULL,
  `item_code` varchar(250) DEFAULT NULL,
  `order_id` int(11) DEFAULT NULL,
  `status` enum('in','out','transfer_out','transfer_in','reserved_in','reserved_out','damage_out','damage_in','return','purchase_out','purchase_delete','sales_return_delete','sales_delete','purchase_return_delete','product_delete','manual_in','manual_out','') NOT NULL DEFAULT 'in',
  `quantity` int(11) NOT NULL,
  `actual_rmb` decimal(15,2) NOT NULL DEFAULT 0.00,
  `total_rmb` decimal(15,2) NOT NULL DEFAULT 0.00,
  `actual_usd` decimal(15,2) DEFAULT 0.00,
  `official_qty` int(11) NOT NULL DEFAULT 0,
  `official_rate_rs` decimal(15,2) NOT NULL DEFAULT 0.00,
  `official_total_rs` decimal(15,2) NOT NULL DEFAULT 0.00,
  `actual_inr` decimal(15,2) DEFAULT 0.00,
  `black_qty` int(11) NOT NULL DEFAULT 0,
  `pending_qty` int(11) NOT NULL DEFAULT 0,
  `black_rate_rs` decimal(15,2) NOT NULL DEFAULT 0.00,
  `black_total_rs` decimal(15,2) NOT NULL DEFAULT 0.00,
  `duty_percent` decimal(5,2) NOT NULL DEFAULT 0.00,
  `duty_amt` decimal(15,2) NOT NULL DEFAULT 0.00,
  `duty_surcharge` decimal(15,2) NOT NULL DEFAULT 0.00,
  `taxable_value` decimal(15,2) NOT NULL DEFAULT 0.00,
  `gst_amt` decimal(15,2) NOT NULL DEFAULT 0.00,
  `total_amt` decimal(15,2) NOT NULL DEFAULT 0.00,
  `received_date` date DEFAULT NULL,
  `batch_no` varchar(250) DEFAULT NULL,
  `expiry_date` date DEFAULT NULL,
  `invoice_no` varchar(250) DEFAULT NULL,
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  `added_date` datetime NOT NULL,
  `added_by_id` int(11) NOT NULL,
  `added_by_name` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
