CREATE TABLE `payments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) NOT NULL,
  `supplier_id` int(11) NOT NULL,
  `supplier_name` varchar(255) NOT NULL,
  `invoice_no` varchar(255) NOT NULL,
  `batch_no` varchar(255) NOT NULL,
  `amount_dollar` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `amount_rs` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `amount_rmb` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `payment_type` enum('official','unofficial','') NOT NULL,
  `bank_account` int(11) NOT NULL DEFAULT 0,
  `bank_account_name` varchar(255) DEFAULT NULL,
  `payment_date` date DEFAULT NULL,
  `narration` text DEFAULT NULL,
  `is_delete` tinyint(1) NOT NULL DEFAULT 0,
  `added_by` int(11) NOT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
