CREATE TABLE `product_variation` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_id` int(11) NOT NULL,
  `size_id` int(11) NOT NULL,
  `size_name` varchar(255) DEFAULT NULL,
  `name` varchar(250) NOT NULL,
  `sku_code` varchar(250) NOT NULL,
  `cartoon_qty` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `net_weight` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `gross_weight` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `length` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `width` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `height` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `cbm` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `image` varchar(250) DEFAULT NULL,
  `is_other` tinyint(1) NOT NULL DEFAULT 0,
  `listed_1` tinyint(1) NOT NULL DEFAULT 1,
  `listed_2` tinyint(1) NOT NULL DEFAULT 1,
  `listed_3` tinyint(1) NOT NULL DEFAULT 1,
  `listed_4` tinyint(1) NOT NULL DEFAULT 1,
  `listed_5` tinyint(1) NOT NULL DEFAULT 1,
  `listed_6` tinyint(1) NOT NULL DEFAULT 1,
  `listed_7` tinyint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  KEY `product_id` (`product_id`),
  KEY `sku_code` (`sku_code`),
  KEY `is_other` (`is_other`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
