CREATE TABLE `purchase_order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `method` varchar(250) DEFAULT NULL,
  `excel_id` varchar(250) DEFAULT NULL,
  `voucher_no` varchar(250) NOT NULL,
  `refrence_no` varchar(250) DEFAULT NULL,
  `date` date NOT NULL,
  `delivery_date` date DEFAULT NULL,
  `company_id` int(11) DEFAULT NULL,
  `company_name` varchar(250) DEFAULT NULL,
  `supplier_id` int(11) NOT NULL,
  `supplier_name` varchar(250) NOT NULL,
  `warehouse_id` int(11) NOT NULL,
  `warehouse_name` varchar(250) NOT NULL,
  `billing_address` longtext NOT NULL,
  `delivery_address` longtext NOT NULL,
  `mode_of_payment` varchar(250) DEFAULT NULL,
  `dispatch` varchar(250) DEFAULT NULL,
  `destination` varchar(250) DEFAULT NULL,
  `other_refrence` varchar(250) DEFAULT NULL,
  `terms_of_delivery` longtext DEFAULT NULL,
  `narration` longtext DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `total_cbm` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `net_sales_value_1` decimal(16,5) DEFAULT 0.00000,
  `discount_type` enum('product','order','') NOT NULL DEFAULT 'product',
  `discount` int(11) DEFAULT 0,
  `discount_amount` decimal(16,5) DEFAULT 0.00000,
  `basic_value` decimal(16,5) DEFAULT 0.00000,
  `total_black_amount_summary` decimal(16,5) DEFAULT 0.00000,
  `gst_type` varchar(20) DEFAULT NULL,
  `cgst_amount` decimal(16,5) DEFAULT 0.00000,
  `sgst_amount` decimal(16,5) DEFAULT 0.00000,
  `igst_amount` decimal(16,5) DEFAULT 0.00000,
  `net_sales_value_2` decimal(16,5) DEFAULT 0.00000,
  `transport_charge` decimal(16,5) DEFAULT 0.00000,
  `transport_gst_type` enum('No','Yes','') DEFAULT '',
  `transport_gst` int(11) DEFAULT 0,
  `transport_gst_amount` decimal(16,5) DEFAULT 0.00000,
  `other_charges_name` varchar(250) DEFAULT NULL,
  `other_charges_amount` decimal(16,5) DEFAULT 0.00000,
  `round_of` decimal(16,5) DEFAULT 0.00000,
  `grand_total` decimal(16,5) DEFAULT 0.00000,
  `inr_rate` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `delivery_status` enum('pending','complete','priority','loading','purchase_in','') NOT NULL DEFAULT 'pending',
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0,
  `added_date` datetime NOT NULL,
  `priority_date` datetime DEFAULT NULL,
  `loading_date` datetime DEFAULT NULL,
  `expected_date` datetime DEFAULT NULL,
  `arrival_date` datetime DEFAULT NULL,
  `completed_date` datetime DEFAULT NULL,
  `boe_no` varchar(255) DEFAULT NULL,
  `boe_date` datetime DEFAULT NULL,
  `source` varchar(255) NOT NULL DEFAULT 'po',
  `added_by_id` int(11) NOT NULL,
  `added_by_name` varchar(250) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=268 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
