CREATE TABLE `purchase_order_product` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) NOT NULL,
  `supplier_id` int(11) NOT NULL,
  `product_type` enum('ready','spare','') NOT NULL DEFAULT '',
  `product_id` int(11) NOT NULL,
  `categories` varchar(255) DEFAULT NULL,
  `sizes` varchar(255) DEFAULT NULL,
  `group_id` varchar(255) DEFAULT NULL,
  `color_id` int(11) DEFAULT NULL,
  `color_name` varchar(255) DEFAULT NULL,
  `product_name` varchar(250) NOT NULL,
  `hsn_code` varchar(250) DEFAULT NULL,
  `item_code` varchar(250) DEFAULT NULL,
  `unit` varchar(20) DEFAULT NULL,
  `quantity` int(11) NOT NULL,
  `white_qty` int(11) NOT NULL DEFAULT 0,
  `black_qty` int(11) NOT NULL DEFAULT 0,
  `cbm` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `total_cbm` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `pending_po_qty` int(11) NOT NULL DEFAULT 0,
  `loading_list_qty` int(11) NOT NULL DEFAULT 0,
  `in_stock_qty` int(11) NOT NULL DEFAULT 0,
  `current_company_qty` int(11) NOT NULL DEFAULT 0,
  `cartoon` int(11) NOT NULL,
  `rate` decimal(16,5) NOT NULL,
  `basic_amount` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `discount` int(11) DEFAULT 0,
  `discount_amount` decimal(16,5) DEFAULT 0.00000,
  `gst` int(11) NOT NULL DEFAULT 0,
  `gst_amount` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `total_val` decimal(16,5) NOT NULL,
  `black_amt` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `black_amt_total` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `grand_total` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `pending` int(11) DEFAULT 0,
  `received` int(11) DEFAULT 0,
  `received_date` date DEFAULT NULL,
  `invoice_no` varchar(250) DEFAULT NULL,
  `is_complete` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=992 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
