CREATE TABLE `raw_products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `is_variation` tinyint(1) NOT NULL DEFAULT 0,
  `commission_id` int(11) NOT NULL,
  `categories` varchar(255) DEFAULT NULL,
  `sizes` varchar(255) DEFAULT NULL,
  `group_id` varchar(255) NOT NULL,
  `color_id` int(11) NOT NULL,
  `color_name` varchar(255) DEFAULT NULL,
  `product_type` enum('import','local','') DEFAULT 'import',
  `type` enum('ready','spare','') DEFAULT '',
  `image` varchar(250) DEFAULT NULL,
  `name` varchar(250) NOT NULL,
  `alias` varchar(255) DEFAULT NULL,
  `item_code` varchar(250) DEFAULT NULL,
  `supplier_id` varchar(255) DEFAULT NULL,
  `supplier_name` TEXT DEFAULT NULL,
  `net_weight` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `gross_weight` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `length` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `width` decimal(16,2) NOT NULL DEFAULT 0.00,
  `height` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `cbm` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `usd_rate` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `actual_usd_rate` decimal(15,2) DEFAULT 0.00,
  `rate` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `unit` varchar(50) NOT NULL,
  `form` varchar(250) DEFAULT NULL,
  `hsn_code` varchar(100) DEFAULT NULL,
  `duty_charge` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `gst_type` enum('Inclusive','Exclusive','') NOT NULL DEFAULT 'Inclusive',
  `product_mrp` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `costing_price` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `status` tinyint(1) NOT NULL DEFAULT 1,
  `amount` decimal(16,5) NOT NULL,
  `is_gst_applicable` tinyint(1) NOT NULL DEFAULT 1,
  `gst` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `gst_amount` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `total_amount` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `min_stock` int(11) NOT NULL DEFAULT 0,
  `intimation` int(11) NOT NULL DEFAULT 0,
  `cartoon_qty` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `listed_1` tinyint(1) NOT NULL DEFAULT 1,
  `listed_2` tinyint(1) NOT NULL DEFAULT 1,
  `listed_3` tinyint(1) NOT NULL DEFAULT 1,
  `listed_4` tinyint(1) NOT NULL DEFAULT 1,
  `listed_5` tinyint(1) NOT NULL DEFAULT 1,
  `listed_6` tinyint(1) NOT NULL,
  `listed_7` tinyint(1) NOT NULL DEFAULT 1,
  `opening_stock` int(11) NOT NULL DEFAULT 0,
  `has_formula` tinyint(1) NOT NULL DEFAULT 0,
  `remark` TEXT DEFAULT NULL,
  `expense` decimal(16,5) NOT NULL DEFAULT 0.00000,
  `is_other_sku` tinyint(1) NOT NULL DEFAULT 0,
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0,
  `added_date` datetime NOT NULL,
  PRIMARY KEY (`id`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;