CREATE TABLE `sales_order_product_batch` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `order_id` int(11) NOT NULL,
  `order_product_id` int(11) NOT NULL,
  `batch_no` varchar(250) DEFAULT NULL,
  `batch_qty` int(11) NOT NULL,
  `avail_white_qty` int(11) NOT NULL DEFAULT 0,
  `avail_black_qty` int(11) NOT NULL DEFAULT 0,
  `qty` int(11) NOT NULL DEFAULT 0,
  `white_qty` int(11) NOT NULL DEFAULT 0,
  `black_qty` int(11) NOT NULL DEFAULT 0,
  `recieved_qty` int(11) NOT NULL DEFAULT 0,
  `recieved_black_qty` int(11) NOT NULL DEFAULT 0,
  `return_qty` int(11) NOT NULL DEFAULT 0,
  `return_black_qty` int(11) NOT NULL DEFAULT 0,
  `amount` decimal(16,2) NOT NULL DEFAULT 0.00,
  `remark` text DEFAULT NULL,
  `bill_amount` decimal(16,2) NOT NULL DEFAULT 0.00,
  `bill_remark` text DEFAULT NULL,
  `bill_total` decimal(16,2) NOT NULL DEFAULT 0.00,
  `gst` decimal(16,2) NOT NULL DEFAULT 0.00,
  `gst_amount` decimal(16,2) NOT NULL DEFAULT 0.00,
  `total_bill_gst_amount` decimal(16,2) NOT NULL DEFAULT 0.00,
  `black_amount` decimal(16,2) NOT NULL DEFAULT 0.00,
  `black_total` decimal(16,2) NOT NULL DEFAULT 0.00,
  `final_total` decimal(16,2) NOT NULL DEFAULT 0.00,
  `added_date` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
