CREATE TABLE `sales_commission` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `order_id` int(11) NOT NULL,
  `order_product_id` int(11) NOT NULL,
  `order_product_batch_id` int(11) NOT NULL,
  `product_id` int(11) NOT NULL,
  `commission_id` int(11) NOT NULL,
  `product_comm` decimal(16,2) NOT NULL DEFAULT 0.00,
  `product_comm_amt` decimal(16,2) NOT NULL DEFAULT 0.00,
  `staff_id` int(11) NOT NULL,
  `staff_comm_id` int(11) NOT NULL,
  `customer_range` varchar(255) DEFAULT NULL,
  `customer_comm` decimal(16,2) NOT NULL DEFAULT 0.00,
  `distributer_comm` decimal(16,2) NOT NULL DEFAULT 0.00,
  `commission_amount` decimal(16,2) NOT NULL DEFAULT 0.00,
  `share_staff_id` int(11) NOT NULL DEFAULT 0,
  `shared_staff_comm_id` int(11) NOT NULL DEFAULT 0,
  `shared_commission` decimal(16,2) NOT NULL DEFAULT 0.00,
  `my_commission` decimal(16,2) NOT NULL DEFAULT 0.00,
  `is_paid` tinyint(1) NOT NULL DEFAULT 0,
  `payment_date` date DEFAULT NULL,
  `remark` text DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
