CREATE TABLE `supplier` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `company_id` int(11) DEFAULT NULL,
  `type` enum('import','local','') DEFAULT 'import',
  `name` varchar(250) NOT NULL,
  `gst_name` varchar(250) DEFAULT NULL,
  `gst_no` varchar(250) DEFAULT NULL,
  `contact_name` varchar(250) DEFAULT NULL,
  `c_code` varchar(250) DEFAULT NULL,
  `contact_no` varchar(250) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `t_code` varchar(255) DEFAULT NULL,
  `tel_no` varchar(255) DEFAULT NULL,
  `address` longtext DEFAULT NULL,
  `address_2` mediumtext DEFAULT NULL,
  `address_3` mediumtext DEFAULT NULL,
  `pincode` varchar(250) DEFAULT NULL,
  `country_id` varchar(250) DEFAULT NULL,
  `country_name` varchar(250) DEFAULT NULL,
  `state_id` int(11) DEFAULT NULL,
  `state_name` varchar(50) DEFAULT NULL,
  `city_id` int(11) DEFAULT NULL,
  `city_name` varchar(50) DEFAULT NULL,
  `state_code` varchar(10) DEFAULT NULL,
  `beneficiary` varchar(250) DEFAULT NULL,
  `account_no` varchar(250) DEFAULT NULL,
  `advising_bank` varchar(250) DEFAULT NULL,
  `bank_address` longtext DEFAULT NULL,
  `swift_code` varchar(250) DEFAULT NULL,
  `signature_image` varchar(255) DEFAULT NULL,
  `outstanding_rmb` DECIMAL(16,2) NOT NULL DEFAULT 0.00,
  `outstanding_inr` DECIMAL(16,2) NOT NULL DEFAULT 0.00,
  `outstanding_usd` DECIMAL(16,2) NOT NULL DEFAULT 0.00,
  `added_by_id` int(11) DEFAULT NULL,
  `added_by_name` varchar(100) DEFAULT NULL,
  `added_date` datetime NOT NULL,
  `is_deleted` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
