CREATE TABLE `sys_users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `type` enum('admin','HR','Inventory','Production Head','Mixing','QC','Filling','Tertiary','staff') DEFAULT NULL,
  `staff_access` int(11) DEFAULT NULL,
  `added_by` int(11) DEFAULT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `email` varchar(50) DEFAULT NULL,
  `date_birth` date DEFAULT NULL,
  `join_date` date DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `alt_phone` varchar(250) DEFAULT NULL,
  `salery` varchar(250) NOT NULL,
  `password` varchar(255) DEFAULT NULL,
  `address` text DEFAULT NULL,
  `state_id` int(11) NOT NULL,
  `state_name` varchar(250) NOT NULL,
  `city_id` int(11) NOT NULL,
  `city_name` varchar(250) NOT NULL,
  `profile_img` varchar(255) DEFAULT NULL,
  `company_id` varchar(255) DEFAULT NULL,
  `aadhar_no` varchar(255) DEFAULT NULL,
  `aadhar_photo` varchar(255) DEFAULT NULL,
  `pan_no` varchar(255) DEFAULT NULL,
  `pan_photo` varchar(255) DEFAULT NULL,
  `remark` text DEFAULT NULL,
  `designation` varchar(250) DEFAULT NULL,
  `role_id` int(11) DEFAULT NULL,
  `access_code` varchar(500) DEFAULT NULL,
  `date_added` datetime DEFAULT NULL,
  `last_modified` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `status` tinyint(1) DEFAULT 0,
  `is_deleted` tinyint(1) NOT NULL DEFAULT 0,
  `is_read` tinyint(1) NOT NULL DEFAULT 0,
  `warehouse_id` int(11) DEFAULT NULL,
  `is_password` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
