CREATE TABLE `warehouse` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(250) NOT NULL,
  `gst_name` varchar(250) DEFAULT NULL,
  `gst_no` varchar(250) DEFAULT NULL,
  `contact_name` varchar(250) DEFAULT NULL,
  `contact_no` varchar(250) DEFAULT NULL,
  `address` longtext DEFAULT NULL,
  `address_2` mediumtext DEFAULT NULL,
  `address_3` mediumtext DEFAULT NULL,
  `pincode` varchar(250) DEFAULT NULL,
  `state_id` int(11) DEFAULT NULL,
  `state_name` varchar(50) DEFAULT NULL,
  `city_id` int(11) DEFAULT NULL,
  `city_name` varchar(50) DEFAULT NULL,
  `state_code` varchar(10) DEFAULT NULL,
  `company_id` int(255) NOT NULL,
  `added_by_id` int(11) DEFAULT NULL,
  `added_by_name` varchar(100) DEFAULT NULL,
  `added_date` datetime NOT NULL,
  `is_deleted` tinyint(1) DEFAULT 0,
  `sort` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
